### ISSUE TITLE
Redesign Project Detail page (horizontal scrolling)

### ISSUE THREAD

**Issue by matthew-ia** [matthew-ia/matthewia-site#13]
### The Concept

The new design is organized into two sections:
- **Brief** – project title, tags, summary, and preview image | above the fold
- **Gallery** – images (and copy) to explain/show off the project | below the fold

Scrolling behavior will be controlled, so when the user tries scrolling down (or clicks the "scroll-down" arrow) while looking at the Brief section, it'll automatically smooth scroll down to fill the screen with the Gallery section. Once in the Gallery, vertical and horizontal scrolling controls the horizontal gallery layout. If the user scrolls up once the gallery is as far as it can scroll to the left, it'll scroll back up to the Brief section. Alternatively, they can click a "scroll-up" arrow that'll replace the scroll-down arrow when the Gallery is in view. 

### // TODO:

- [x] Build Brief component
  - [x] Handle vertical scrolling behavior
- [x] Build Gallery component
  - [x] Handle vertical scrolling behavior
  - [x] Handle horizontal scrolling behavior
- [ ] ~~Handle manual scrollbar scrolling in Brief section (I don't want the user to necessarily be able to scroll the full width; maybe a macOS like "you're at the end of the scroll zone" behavior)~~
---

### Mockups

![screen shot 2018-08-21 at 1 16 27 am](https://user-images.githubusercontent.com/17885141/44381776-e1ef0380-a4df-11e8-9135-6784ec3cc33c.png)
![screen shot 2018-08-21 at 1 16 36 am](https://user-images.githubusercontent.com/17885141/44381779-e3b8c700-a4df-11e8-99bd-3a318774d249.png)
